variable "instance_name" {}
variable "instance_zone" {}
variable "instance_type" {}
variable "instance_network" {}
variable "sa_email" {}
variable "instance_subnetwork" {}
variable "project_name" {}
variable "discord_app_id" {}
variable "project_region" {}